const $ = (id) => document.getElementById(id);
let cfg;
const api = (p, o) => fetch('/api' + p, o).then(async (r) => { const j = await r.json(); if (!r.ok) throw new Error(j.error || 'Error'); return j; });
const post = (p, b) => api(p, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(b) });
const fileToUri = (f) => new Promise((ok) => { if (!f) return ok(null); const r = new FileReader(); r.onload = () => ok(r.result); r.readAsDataURL(f); });
const opts = (a) => a.map((x) => `<option>${x}</option>`).join('');

async function init() {
  cfg = await api('/config');
  ['r-group', 'd-group'].forEach((i) => ($(i).innerHTML = opts(cfg.groups)));
  $('r-comp').innerHTML = opts(cfg.components);
  ['r-area', 'd-area'].forEach((i) => ($(i).innerHTML = opts(cfg.areas)));
  $('r-group').value = 'B+';
  document.querySelectorAll('nav button').forEach((b) => (b.onclick = () => show(b.dataset.t)));
  refreshDonors();
}
function show(t) {
  document.querySelectorAll('nav button').forEach((b) => b.classList.toggle('on', b.dataset.t === t));
  document.querySelectorAll('section').forEach((s) => s.classList.toggle('on', s.id === t));
  if (t === 'list') loadRequests(); if (t === 'inbox') loadAlerts(); if (t === 'don') refreshDonors();
}
const donorCard = (d) => `<div class="card"><b>${d.name}</b> <span class="pill red">${d.bloodGroup}</span>${d.verified ? '<span class="pill ok">✔ verified</span>' : '<span class="pill">unverified</span>'}
 <div class="note">${d.area}${d.km != null ? ' · ' + d.km + ' km away · match ' + d.score + '%' : ''} · 🔒 contact via platform${d.alerted ? ' · 🔔 alerted' : ''}${d.accepted ? ' · ✅ accepted' : ''}${d.cooldownDays ? ' · cooldown ' + d.cooldownDays + 'd' : ''}${d.flagged ? ' · ⚠ flagged' : ''}</div>
 ${d.idUrl ? `<img src="${d.idUrl}" width="120" alt="ID thumbnail">` : ''}</div>`;
async function refreshDonors() {
  const ds = await api('/donors');
  $('d-list').innerHTML = ds.slice().reverse().map(donorCard).join('');
  $('i-donor').innerHTML = ds.map((d) => `<option value="${d.id}">${d.name} (${d.bloodGroup}, ${d.area})</option>`).join('');
}
$('d-go').onclick = async () => {
  $('d-err').textContent = '';
  try {
    const d = await post('/donors', { name: $('d-name').value, phone: $('d-phone').value, bloodGroup: $('d-group').value, area: $('d-area').value,
      lastDonation: $('d-last').value, idImage: await fileToUri($('d-file').files[0]) });
    $('d-out').innerHTML = '<p>✅ Registered! ' + (d.verified ? 'ID received - verified badge added.' : 'Add an ID photo to get verified.') + '</p>';
    refreshDonors();
  } catch (e) { $('d-err').textContent = e.message; }
};
$('r-go').onclick = async () => {
  $('r-err').textContent = '';
  try {
    const r = await post('/requests', { patient: $('r-patient').value, bloodGroup: $('r-group').value, units: $('r-units').value, area: $('r-area').value,
      urgency: $('r-urg').value, phone: $('r-phone').value, hospital: $('r-hosp').value, note: $('r-note').value, component: $('r-comp').value, reportImage: await fileToUri($('r-file').files[0]) });
    $('r-out').innerHTML = reqCard(r);
  } catch (e) { $('r-err').textContent = e.message; }
};
function reqCard(r) {
  const i = cfg.statuses.indexOf(r.status), flagged = r.status === 'Flagged';
  const acc = r.matches.filter((m) => m.accepted);
  return `<div class="card"><b>${r.component} ${r.bloodGroup}</b> for ${r.patient} · ${r.area} <span class="pill red">${r.urgency}</span> <span class="note">${r.id}</span>
  ${flagged ? `<div class="warn bad">⚠ Held for review - no alerts sent. ${r.flags.join('; ') || 'Reported by users.'}<br><button class="btn sm o" onclick="act('${r.id}','clear')">Reviewer: clear request</button></div>`
    : `<div class="steps">${cfg.statuses.map((_, k) => `<i class="${k <= i ? 'd' : ''}"></i>`).join('')}</div><b>${r.status}</b> · ${r.alerted.length} donors alerted · search radius ${r.radiusKm} km${r.stage ? ' (escalated x' + r.stage + ')' : ''}`}
  ${r.bankAlerts.length ? `<div class="warn">🏥 Blood banks alerted: ${r.bankAlerts.join(', ')}</div>` : ''}
  <img class="cardimg" src="${r.cardUrl}" alt="Emergency request card (Cloudinary)">
  <div class="note">Shareable emergency card generated by Cloudinary - long-press to save and forward on WhatsApp.</div>
  ${r.reportUrl ? `<p class="note">Medical report:</p><img src="${r.reportUrl}" width="160">` : ''}
  <div class="tl">${r.timeline.map((t) => '• ' + new Date(t.at).toLocaleTimeString() + ' ' + t.text).join('<br>')}</div>
  ${r.messages.length ? '<h4>Platform chat (numbers hidden)</h4>' + r.messages.map((m) => `<div class="msg"><b>${m.from}</b>: ${m.text}${m.warn ? ' <span class="pill red">⚠ money mentioned - donation is never paid</span>' : ''}</div>`).join('') : ''}
  ${acc.map((m) => `<div class="row"><input id="m-${r.id}-${m.id}" placeholder="Message ${m.name} (relay)"><button class="btn sm" onclick="sendMsg('${r.id}','${m.id}','requester')">Send</button></div>`).join('')}
  <h4>Matched donors (best first)</h4>${r.matches.length ? r.matches.map(donorCard).join('') : '<p class="note">No eligible compatible donor in range yet - escalation will widen the search and alert blood banks.</p>'}
  ${flagged ? '' : `<div>${cfg.statuses.slice(2).map((s) => `<button class="btn sm" onclick="setStatus('${r.id}','${s}')">${s}</button>`).join('')}
  <button class="btn sm o" onclick="act('${r.id}','escalate')">⏩ Simulate ${cfg.escalationMinutes} min with no reply</button></div>`}
  <button class="btn sm o" onclick="report('request','${r.id}')">🚩 Report: asked for money / fake</button></div>`;
}
async function act(id, a) { await post(`/requests/${id}/${a}`, {}); loadRequests(); }
async function sendMsg(id, donorId, from) { const el = $(`m-${id}-${donorId}`) || $(`im-${id}`); if (!el.value) return; await post(`/requests/${id}/message`, { text: el.value, donorId, from }); from === 'donor' ? loadAlerts() : loadRequests(); }
async function report(kind, id) { const r = await post('/reports', { kind, id, reason: 'money demand / fake' }); alert(r.flagged ? 'Thanks - this is now flagged and removed from matching.' : 'Thanks - reported. One more report auto-flags it.'); loadRequests(); }
async function setStatus(id, status) { await post(`/requests/${id}/status`, { status }); loadRequests(); }
async function loadRequests() {
  const rs = await api('/requests');
  $('l-out').innerHTML = rs.length ? rs.map((r) => reqCard(r)).join('') : '<p class="note">No requests yet.</p>';
}
async function loadAlerts() {
  const id = $('i-donor').value; if (!id) return;
  const [a, rs] = await Promise.all([api('/alerts?donor=' + id), api('/requests')]);
  $('i-out').innerHTML = a.length ? a.map((x) => { const r = rs.find((q) => q.id === x.requestId); const msgs = r ? r.messages.filter((m) => !m.donorId || m.donorId === id) : [];
    return `<div class="card">🔔 ${x.text}<div class="note">${new Date(x.at).toLocaleString()} · ${x.requestId} · requester contact hidden</div>
    ${x.accepted ? '<span class="pill ok">✅ You accepted</span>' : x.status === 'Flagged' ? '<span class="pill">held for review</span>' : `<button class="btn sm g" onclick="accept('${x.requestId}','${id}')">I can donate</button>`}
    ${msgs.map((m) => `<div class="msg"><b>${m.from}</b>: ${m.text}</div>`).join('')}
    ${x.accepted ? `<div class="row"><input id="im-${x.requestId}" placeholder="Reply via platform"><button class="btn sm" onclick="sendMsg('${x.requestId}','${id}','donor')">Send</button></div>` : ''}
    <button class="btn sm o" onclick="report('request','${x.requestId}')">🚩 Report</button></div>`; }).join('') : '<p class="note">No alerts for this donor yet.</p>';
}
async function accept(rid, did) { await post(`/requests/${rid}/accept`, { donorId: did }); loadAlerts(); }
$('i-donor').onchange = loadAlerts;
init().then(() => { if (location.hash === '#list') show('list'); });
