const $ = (id) => document.getElementById(id);
let cfg;
const api = (p, o) => fetch('/api' + p, o).then(async (r) => { const j = await r.json(); if (!r.ok) throw new Error(j.error || 'Error'); return j; });
const post = (p, b) => api(p, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(b) });
const fileToUri = (f) => new Promise((ok) => { if (!f) return ok(null); const r = new FileReader(); r.onload = () => ok(r.result); r.readAsDataURL(f); });
const opts = (a) => a.map((x) => `<option>${x}</option>`).join('');

async function init() {
  cfg = await api('/config');
  ['r-group', 'd-group'].forEach((i) => ($(i).innerHTML = opts(cfg.groups)));
  ['r-area', 'd-area'].forEach((i) => ($(i).innerHTML = opts(cfg.areas)));
  $('r-group').value = 'B+';
  document.querySelectorAll('nav button').forEach((b) => (b.onclick = () => show(b.dataset.t)));
  refreshDonors();
}
function show(t) {
  document.querySelectorAll('nav button').forEach((b) => b.classList.toggle('on', b.dataset.t === t));
  document.querySelectorAll('section').forEach((s) => s.classList.toggle('on', s.id === t));
  if (t === 'list') loadRequests(); if (t === 'inbox') loadAlerts(); if (t === 'don') refreshDonors();
}
const donorCard = (d) => `<div class="card"><b>${d.name}</b> <span class="pill red">${d.bloodGroup}</span>${d.verified ? '<span class="pill ok">✔ verified</span>' : '<span class="pill">unverified</span>'}
 <div class="note">${d.area}${d.km != null ? ' · ' + d.km + ' km away · match ' + d.score + '%' : ''} · ${d.phone}${d.alerted ? ' · 🔔 alerted' : ''}</div>
 ${d.idUrl ? `<img src="${d.idUrl}" width="120" alt="ID thumbnail">` : ''}</div>`;
async function refreshDonors() {
  const ds = await api('/donors');
  $('d-list').innerHTML = ds.slice().reverse().map(donorCard).join('');
  $('i-donor').innerHTML = ds.map((d) => `<option value="${d.id}">${d.name} (${d.bloodGroup}, ${d.area})</option>`).join('');
}
$('d-go').onclick = async () => {
  $('d-err').textContent = '';
  try {
    const d = await post('/donors', { name: $('d-name').value, phone: $('d-phone').value, bloodGroup: $('d-group').value, area: $('d-area').value,
      lastDonation: $('d-last').value, idImage: await fileToUri($('d-file').files[0]) });
    $('d-out').innerHTML = '<p>✅ Registered! ' + (d.verified ? 'ID received - verified badge added.' : 'Add an ID photo to get verified.') + '</p>';
    refreshDonors();
  } catch (e) { $('d-err').textContent = e.message; }
};
$('r-go').onclick = async () => {
  $('r-err').textContent = '';
  try {
    const r = await post('/requests', { patient: $('r-patient').value, bloodGroup: $('r-group').value, units: $('r-units').value, area: $('r-area').value,
      urgency: $('r-urg').value, phone: $('r-phone').value, hospital: $('r-hosp').value, reportImage: await fileToUri($('r-file').files[0]) });
    $('r-out').innerHTML = reqCard(r, true);
  } catch (e) { $('r-err').textContent = e.message; }
};
function reqCard(r, big) {
  const i = cfg.statuses.indexOf(r.status);
  return `<div class="card"><b>${r.bloodGroup}</b> for ${r.patient} · ${r.area} <span class="pill red">${r.urgency}</span> <span class="note">${r.id}</span>
  <div class="steps">${cfg.statuses.map((_, k) => `<i class="${k <= i ? 'd' : ''}"></i>`).join('')}</div><b>${r.status}</b> · ${r.alerted.length} donors alerted
  <img class="cardimg" src="${r.cardUrl}" alt="Emergency request card (Cloudinary)">
  <div class="note">Shareable emergency card generated by Cloudinary - long-press to save and forward on WhatsApp.</div>
  ${r.reportUrl ? `<p class="note">Medical report:</p><img src="${r.reportUrl}" width="160">` : ''}
  <h4>Matched donors (best first)</h4>${r.matches.length ? r.matches.map(donorCard).join('') : '<p class="note">No eligible compatible donor nearby yet - widen area or contact a blood bank.</p>'}
  <div>${cfg.statuses.slice(1).map((s) => `<button class="btn sm" onclick="setStatus('${r.id}','${s}')">${s}</button>`).join('')}</div></div>`;
}
async function setStatus(id, status) { await post(`/requests/${id}/status`, { status }); loadRequests(); }
async function loadRequests() {
  const rs = await api('/requests');
  $('l-out').innerHTML = rs.length ? rs.map((r) => reqCard(r)).join('') : '<p class="note">No requests yet.</p>';
}
async function loadAlerts() {
  const id = $('i-donor').value; if (!id) return;
  const a = await api('/alerts?donor=' + id);
  $('i-out').innerHTML = a.length ? a.map((x) => `<div class="card">🔔 ${x.text}<div class="note">${new Date(x.at).toLocaleString()} · ${x.requestId}</div></div>`).join('') : '<p class="note">No alerts for this donor yet.</p>';
}
$('i-donor').onchange = loadAlerts;
init().then(() => { if (location.hash === '#list') show('list'); });
