services:
  - type: web
    name: blood-network
    runtime: node
    plan: free
    buildCommand: echo "no build step"
    startCommand: node server.js
    envVars:
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
